# Generated by Django 4.1.7 on 2023-02-21 09:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('squad_number', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='players')),
                ('position', models.CharField(blank=True, choices=[('GOALKEEPER', 'Goalkeeper'), ('DEFENDER', 'Defender'), ('MIDFIELDER', 'Midfielder'), ('STRIKER', 'Striker')], max_length=15)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('LOAN', 'On Loan'), ('SOLD', 'Sold')], max_length=15)),
                ('availability', models.CharField(blank=True, choices=[('INJURED', 'Injured'), ('SUSPENDED', 'Suspended'), ('LEAVE', 'On Leave')], max_length=15)),
                ('club_appearances', models.PositiveIntegerField(blank=True, help_text='Total club appearances since joining the club.', null=True)),
                ('goals', models.PositiveIntegerField(blank=True, help_text='Total goals since joining the club.', null=True)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('yellow_cards', models.PositiveIntegerField(blank=True, help_text='Total yellow cards since joining the club.', null=True)),
                ('red_cards', models.PositiveIntegerField(blank=True, help_text='Total red cards since joining the club.', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.CharField(blank=True, help_text='Height in cm.', max_length=10)),
                ('weight', models.CharField(blank=True, help_text='Weight in kg.', max_length=10)),
                ('previous_clubs', models.CharField(blank=True, max_length=255)),
                ('biography', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ['squad_number'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='staff')),
                ('staff', models.CharField(choices=[('TECHNICAL', 'Technical Crew'), ('MANAGEMENT', 'Club Management'), ('BACKROOM', 'Backroom Staff')], max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Uncheck this if the Official is no longer with the club.')),
            ],
            options={
                'ordering': ['name', 'staff'],
            },
        ),
    ]
